language: java
jdk_switcher:
- ibmjava8
before_script:
- sudo apt-get install ant-optional
script: ant build
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: maya.aitpune@gmail.com
  password: $PASSWORD
  organization: Amdocs_Org
  space: dev
  api: https://api.eu-gb.bluemix.net
  on:
    branch: master