language: java
jdk_switcher:
- ibmjava8
before_script:
- sudo apt-get install ant-optional
script: ant build
deploy:
  provider: heroku
  api_key: e1760e84-36ed-4342-a432-4c5d8bdaeaf1
  app: travis-ci-demo
