language: java
jdk:
  - oraclejdk8
before_script:
- sudo apt-get install ant-optional
script: ant build
deploy:
  provider: bluemixcloudfoundry
  skip_cleanup: true
  manifest: manifest.yml
  username: $USER
  password: $PASSWORD
  organization: Maya_Org
  space: dev
  api: https://api.eu-gb.bluemix.net
  on:
    branch: master
